name: cotti_client
description: 库迪咖啡APP客户端
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.4+11

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_picker: 2.0.2
  #高德定位
  amap_flutter_location: ^3.0.0
  # 系统权限
  permission_handler: ^8.3.0
  #升级库
  joymo_app_upgrade: ^1.0.7-nullsafety.3
  decimal: ^2.0.0
  #svg图片加载
  flutter_svg: ^0.23.0+1
  #检测可见性
  visibility_detector: ^0.2.2
  #下拉刷新
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.17
  #lottie动画
  lottie: ^1.2.1
  #图片缓存
  cached_network_image: ^3.2.0
  #轮播图
  card_swiper: ^2.0.0
  #播放器组件
  video_player: 2.2.11
  #webView
  webview_flutter: ^3.0.0
  #webview扩展
  flutter_inappwebview: 5.6.0+2
  #粘性header
  sticky_headers: ^0.2.0
  #微信
  fluwx: 3.12.2
  #支付宝
  tobias: 2.4.1
  #计算组件位置信息
  rect_getter: ^1.1.0
  package_info: ^2.0.2
  # 添加神策 flutter plugin
  sensors_analytics_flutter_plugin: 2.3.0
  #侧滑删除组件
  flutter_slidable: ^1.3.2
  chips_choice_null_safety: ^2.0.4
  modal_bottom_sheet: ^2.0.0
  wechat_assets_picker: 6.3.1
  wechat_camera_picker: 2.6.5
  path_provider: ^2.0.9
  flutter_image_compress: 1.1.3
  #二维码生成
  pretty_qr_code: ^2.0.2
  #保存图片到相册
  image_gallery_saver: ^1.7.1
  #城市列表
  azlistview: 2.0.0-nullsafety.0
  shimmer: ^2.0.0

  amap_flutter_map:
    git:
      url: https://flutter-readonly:flutter-readonly@git.yummy.tech/frontend/flutterplugin.git
      path: amap_flutter_map
      ref: dev
  cotticommon:
    git:
      url: https://flutter-readonly:flutter-readonly@git.yummy.tech/frontend/cotticommon.git
      ref: master
  abitelogin:
    git:
      url: https://flutter-readonly:flutter-readonly@git.yummy.tech/frontend/abitelogin.git
      ref: cotti_login
  flutter_umeng:
    git:
      url: https://flutter-readonly:flutter-readonly@git.yummy.tech/frontend/flutterplugin.git
      path: flutter_umeng
      ref: dev
  jpush_flutter:
    git:
      url: https://flutter-readonly:flutter-readonly@git.yummy.tech/frontend/jpush-plugin.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/mine/
    - assets/images/splash/
    - assets/images/home/
    - assets/images/menu/
    - assets/images/menu/2.0x/
    - assets/images/menu/3.0x/
    - assets/images/tab_bar/
    - assets/images/my_video_player/
    - assets/images/shopping_cart/
    - assets/images/order/order_detail/
    - assets/images/order/order_detail/2.0x/
    - assets/images/order/order_detail/3.0x/
    - assets/images/order/order_list/
    - assets/images/order/order_confirm/
    - assets/images/order/order_evaluate/
    - assets/images/order/comment/
    - assets/images/lotti/
    - assets/images/address/
    - assets/images/product/
    - assets/images/shop/
    - assets/images/city/
  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: DDP4
      fonts:
        - asset: assets/fonts/D-DIN-PRO-400-Regular.otf
    - family: DDP5
      fonts:
        - asset: assets/fonts/D-DIN-PRO-500-Medium.otf
    - family: DDP6
      fonts:
        - asset: assets/fonts/D-DIN-PRO-600-SemiBold.otf
    - family: DDP7
      fonts:
        - asset: assets/fonts/D-DIN-PRO-700-Bold.otf
    - family: DDP8
      fonts:
        - asset: assets/fonts/D-DIN-PRO-800-ExtraBold.otf
    - family: MON
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: SYHT
      fonts:
        - asset: assets/fonts/SourceHanSansSC-Medium.otf
