/// Description:
/// Author: xingguo.lei@abite.com
/// Date: 2022/10/11 2:08 PM
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class IconFont {
  static const String _family = 'iconfont';
  IconFont._();
  static const IconData icon_weixuanzhong2 = IconData(0xe6a5, fontFamily: _family);
  static const IconData icon_shequnfuli = IconData(0xe608, fontFamily: _family);
  static const IconData icon_dizhiguanli = IconData(0xe609, fontFamily: _family);
  static const IconData icon_shezhi = IconData(0xe60a, fontFamily: _family);
  static const IconData icon_kefubangzhu = IconData(0xe60b, fontFamily: _family);
  static const IconData icon_wode_duihuanquan = IconData(0xe607, fontFamily: _family);
  static const IconData icon_xingzhuang1 = IconData(0xe606, fontFamily: _family);
  static const IconData icon_xingzhuang = IconData(0xe603, fontFamily: _family);
  static const IconData icon_bianjidianhua = IconData(0xe605, fontFamily: _family);
  static const IconData icon_qianggou_jiahao = IconData(0xe6a4, fontFamily: _family);
  static const IconData icon_shuakaqueshengtubiao = IconData(0xe604, fontFamily: _family);
  static const IconData icon_wechat = IconData(0xe6a3, fontFamily: _family);
  static const IconData icon_zhifubao = IconData(0xe6a2, fontFamily: _family);
  static const IconData icon_liebiaoshangla = IconData(0xe6a0, fontFamily: _family);
  static const IconData icon_liebiaoxiala = IconData(0xe6a1, fontFamily: _family);
  static const IconData icon_select = IconData(0xe69f, fontFamily: _family);
  static const IconData icon_shoucang = IconData(0xe69e, fontFamily: _family);
  static const IconData icon_caidan_zhankaishouqingshangjiantou = IconData(0xe69c, fontFamily: _family);
  static const IconData icon_caidan_zhankaishouqingxiajiantou = IconData(0xe69d, fontFamily: _family);
  static const IconData icon_daohang1 = IconData(0xe696, fontFamily: _family);
  static const IconData icon_shanchu1 = IconData(0xe697, fontFamily: _family);
  static const IconData icon_shixin = IconData(0xe698, fontFamily: _family);
  static const IconData icon_shangjiantou1 = IconData(0xe699, fontFamily: _family);
  static const IconData icon_kongxin = IconData(0xe69a, fontFamily: _family);
  static const IconData icon_xiajiantou1_copy = IconData(0xe69b, fontFamily: _family);
  static const IconData icon_xiuxixiajiantou = IconData(0xe695, fontFamily: _family);
  static const IconData icon_weixuanzhong1 = IconData(0xe601, fontFamily: _family);
  static const IconData icon_sousuo1 = IconData(0xe694, fontFamily: _family);
  static const IconData icon_youjiantou1 = IconData(0xe68f, fontFamily: _family);
  static const IconData icon_a_ = IconData(0xe690, fontFamily: _family);
  static const IconData icon_peisongfei = IconData(0xe68e, fontFamily: _family);
  static const IconData icon_yonghu = IconData(0xe68c, fontFamily: _family);
  static const IconData icon_dizhi = IconData(0xe68d, fontFamily: _family);
  static const IconData icon_jiahao = IconData(0xe68a, fontFamily: _family);
  static const IconData icon_zuojiantou = IconData(0xe68b, fontFamily: _family);
  static const IconData icon_dancengchuangguanbi = IconData(0xe67a, fontFamily: _family);
  static const IconData icon_xuanzhong = IconData(0xe687, fontFamily: _family);
  static const IconData icon_shanchu = IconData(0xe688, fontFamily: _family);
  static const IconData icon_juli = IconData(0xe689, fontFamily: _family);
  static const IconData icon_shangjiantou = IconData(0xe692, fontFamily: _family);
  static const IconData icon_xiangqing_copy = IconData(0xe693, fontFamily: _family);
  static const IconData icon_daohang = IconData(0xe675, fontFamily: _family);
  static const IconData icon_dengpao = IconData(0xe676, fontFamily: _family);
  static const IconData icon_jianhao = IconData(0xe677, fontFamily: _family);
  static const IconData icon_bukexuan = IconData(0xe678, fontFamily: _family);
  static const IconData icon_xiajiantou_copy = IconData(0xe691, fontFamily: _family);
  static const IconData icon_aixin = IconData(0xe679, fontFamily: _family);
  static const IconData icon_shuaxin = IconData(0xe67b, fontFamily: _family);
  static const IconData icon_shanghuajiantou = IconData(0xe67c, fontFamily: _family);
  static const IconData icon_sousuo = IconData(0xe67d, fontFamily: _family);
  static const IconData icon_xiajiantou = IconData(0xe67e, fontFamily: _family);
  static const IconData icon_lianxidianhua = IconData(0xe67f, fontFamily: _family);
  static const IconData icon_dingweichengshi = IconData(0xe680, fontFamily: _family);
  static const IconData icon_weixuanzhong = IconData(0xe681, fontFamily: _family);
  static const IconData icon_xuanzechengshixiala = IconData(0xe682, fontFamily: _family);
  static const IconData icon_youjiantou = IconData(0xe683, fontFamily: _family);
  static const IconData icon_mendian = IconData(0xe684, fontFamily: _family);
  static const IconData icon_xiangqing = IconData(0xe685, fontFamily: _family);
  static const IconData icon_yijianqingchu = IconData(0xe686, fontFamily: _family);
  static const IconData icon_wechat_color = IconData(0xe62e, fontFamily: _family);
  static const IconData icon_gift = IconData(0xe631, fontFamily: _family);
  static const IconData icon_system = IconData(0xe632, fontFamily: _family);
  static const IconData icon_help = IconData(0xe633, fontFamily: _family);
  static const IconData icon_address = IconData(0xe634, fontFamily: _family);
  static const IconData icon_help_color = IconData(0xe639, fontFamily: _family);
  static const IconData icon_failure = IconData(0xe63d, fontFamily: _family);
  static const IconData icon_pay = IconData(0xe641, fontFamily: _family);
  static const IconData icon_less = IconData(0xe645, fontFamily: _family);
  static const IconData icon_copy = IconData(0xe646, fontFamily: _family);
  static const IconData icon_more_down_01 = IconData(0xe647, fontFamily: _family);
  static const IconData icon_more_down = IconData(0xe648, fontFamily: _family);
  static const IconData icon_shopping_02 = IconData(0xe649, fontFamily: _family);
  static const IconData icon_add = IconData(0xe64a, fontFamily: _family);
  static const IconData icon_add_02 = IconData(0xe64b, fontFamily: _family);
  static const IconData icon_tips = IconData(0xe64c, fontFamily: _family);
  static const IconData icon_add_01 = IconData(0xe64d, fontFamily: _family);
  static const IconData icon_unselect = IconData(0xe650, fontFamily: _family);
  static const IconData icon_close = IconData(0xe65c, fontFamily: _family);
  static const IconData icon_time = IconData(0xe663, fontFamily: _family);
  static const IconData icon_address_01 = IconData(0xe665, fontFamily: _family);
  static const IconData icon_left = IconData(0xe666, fontFamily: _family);
  static const IconData icon_Fullscreen = IconData(0xe668, fontFamily: _family);
  static const IconData icon_Exitfullscreen = IconData(0xe667, fontFamily: _family);
  static const IconData icon_clean = IconData(0xe669, fontFamily: _family);
  static const IconData icon_search = IconData(0xe66a, fontFamily: _family);
  static const IconData icon_paysuccess = IconData(0xe66b, fontFamily: _family);
  static const IconData icon_right = IconData(0xe66c, fontFamily: _family);
  static const IconData icon_cargo = IconData(0xe66e, fontFamily: _family);
  static const IconData icon_success = IconData(0xe66f, fontFamily: _family);
  static const IconData icon_fail = IconData(0xe670, fontFamily: _family);
  static const IconData icon_edit = IconData(0xe671, fontFamily: _family);
  static const IconData icon_backhome = IconData(0xe673, fontFamily: _family);
  static const IconData icon_help_color_copy = IconData(0xe674, fontFamily: _family);
  static const IconData icon_tanhao = IconData(0xe602, fontFamily: _family);
}